[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "lnlabs-agent"
version = "0.0.1"
description = "Desktop agent for LNLabs"
dependencies = [
  "requests",
  "platformdirs",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
